### ISSUE TITLE
The schema for x-correlator should be relaxed - UUID format is not needed 

### ISSUE THREAD

**Issue by rartych** [camaraproject/SimpleEdgeDiscovery#42]
**Problem description**
The schema for x-correlator is defined as follows:     
```
  schema:
       type: string
       format: uuid
```
The format was removed from API design guidelines and [CAMARA_common](https://github.com/camaraproject/Commonalities/blob/fd1e38ab1225cafd73915d1f3b92c5e783a181c7/artifacts/CAMARA_common.yaml#L14)

**Expected behavior**
Remove line 323:
https://github.com/camaraproject/SimpleEdgeDiscovery/blob/cb6af63f4fc88e768f07fdfb2600470843cf460f/code/API_definitions/simple-edge-discovery.yaml#L323

**Alternative solution**

**Additional context**
https://github.com/camaraproject/Commonalities/pull/168

**Comment by Kevsy** [comment]
🤦 missed that one! Thanks @rartych , fixed in https://github.com/camaraproject/SimpleEdgeDiscovery/pull/41/commits/93554d97fc83ac6f37438186c6b3496d413a01a4

**Comment by Kevsy** [comment]
Fixed in #41
