### ISSUE TITLE
Do we need a tagged release in this new repository?

### ISSUE THREAD

**Issue by MarkCornall** [camaraproject/SimpleEdgeDiscovery#7]
**Problem description**
This is moved from the Edge repository but there is no longer a tagged release here.

**Expected action**
Please consider if a tagged release is needed here or something to refer back to old repository for old tagged releases. Although I may have completely missed that ! . Thank you

**Comment by Kevsy** [comment]
Hi Mark - see discussion in https://github.com/camaraproject/SimpleEdgeDiscovery/pull/4 ,  we will make the first tagged release after Commonalities 0.4 (end June). Last tagged release was 0.93 in the Edge Cloud repository, but not recommended as it does not have the newly agree resource structure.

**Comment by Kevsy** [comment]
@MarkCornall if that answer above is ok please can you close? Or let me know if not -  Ta!

**Comment by MarkCornall** [comment]
ok to close thank you Kevin
